### ISSUE TITLE
Sound don't work on android (sound.state, sound.get_pos() and sound.length)

### ISSUE THREAD

**Issue by Chipsterjulien** [kivy/kivy#2776]
First, sorry for my poor english.
I make a little script and use latest kivy (1.9-dev).
1. my_sound.state always return 'play' after my_sound.play() even my_sound was finishing
2. my_sound.length always return 0
3. my_sound.get_pos() always return 0 after my_sound.play()

You must put 3 files (1.mp3, 2.mp3 and 3.mp3 recording with audacity) in Sound directory.
See tree command:

```
.
├── buildozer.spec
├── main.py
├── Sound
│   ├── 1.mp3
│   ├── 2.mp3
│   └── 3.mp3
└── sound_issue.kv

1 directory, 6 files
```

buildozer.spec:

```
[app]
title = sound_issue
package.name = sound_issue
package.domain = org.test
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,txt,mp3
version.regex = __version__ = '(.*)'
version.filename = %(source.dir)s/main.py
requirements = kivy==master
orientation = all
fullscreen = 1
[buildozer]
log_level = 1
```

sound_issue.kv:

```
<RootForm>
RootForm:
    lenn: sndlength
    poss: sndposition
    statt: sndstate
    orientation: 'vertical'

    Label:
        text: 'Sound length:'
        id: sndlength
    Label:
        text: 'Sound position:'
        id: sndposition
    Label:
        text: 'Sound state:'
        id: sndstate
    BoxLayout:
        orientation: 'horizontal'

        Button:
            text: 'Quit'
            on_press: root.quit()
        Button:
            text: 'Play many sounds'
            on_press: root.play()
```

main.py:

```
# -*- coding: utf-8 -*-

__version__ = '0.1'

from kivy.app import App
from kivy.properties import ObjectProperty
from kivy.core.audio import SoundLoader
from kivy.uix.boxlayout import BoxLayout
from kivy.clock import Clock

class RootForm(BoxLayout):
    lenn = ObjectProperty(None)
    poss = ObjectProperty(None)
    statt = ObjectProperty(None)
    my_sound = None
    sounds = ['1.mp3', '2.mp3', '3.mp3']

    def quit(self):
        Sound_issue.get_running_app().stop()

    def play(self):
        self.tab_pos = 0
        self.playing()

    def playing(self):
        self.my_sound = SoundLoader.load('Sound/' + self.sounds[self.tab_pos])
        self.lenn.text = 'Sound length: {}'.format(self.my_sound.length)
        self.poss.text = 'Sound position: {}'.format(self.my_sound.get_pos())
        self.statt.text = 'Sound state: {}'.format(self.my_sound.state)
        self.my_sound.play()
        Clock.schedule_interval(self._test_end, 0.2)

    def _test_end(self, dt):
        self.lenn.text = 'Sound length: {}'.format(self.my_sound.length)
        self.poss.text = 'Sound position: {}'.format(self.my_sound.get_pos())
        self.statt.text = 'Sound state: {}'.format(self.my_sound.state)

        if self.my_sound.state == 'stop':
            self.tab_pos += 1
            if self.tab_pos < 3:
                self.my_sound.unload()
                self.my_sound = None
                self.my_sound = SoundLoader.load('Sound/' + self.sounds[self.tab_pos])
                self.playing()
            else:
                return False

class Sound_issue(App):
    def on_pause(self):
        return True
```

**Comment by tito** [comment]
The pos/length has been fixed in https://github.com/kivy/python-for-android/commit/9b8fad762a8ecafca0d21678f602a2fc6abde623.

It seems that a recent changes into kivy (1.9) just highlighted this one. Thanks for reporting.

**Comment by susheel-smrt** [comment]
Don't use mp3 and take a build with buildozer

**Comment by Arctia** [comment]
I have a problem similar to this one. I can't get the sound.get_pos() to work correctly on android app, it always return 0, while in my linux system is working correctly. 
kivy version 1.10.0 
buildozer 0.33
sound file: .ogg

**Comment by scattenlaeufer** [comment]
This issue seems to be not entirely fixed. I created a small [roof of concept for the issue](https://github.com/scattenlaeufer/kivy_sound_issue) and tested it with:

* kivy version: 1.11.1 (7947abfbb77cb50c6d7cce7c8739ab630e028034 to be precise)
* buildozer version: 0.40.dev0
* Android versions: 7.1.2 & 9

On a press of the button, a sound plays and the label should show the current position using `get_pos()`. On Linux this works as expected, but on Android this function only returns `0`.
