### ISSUE TITLE
Horizontal scrolling with mouse pad triggers left mouse clicking on Ubuntu 14.04

### ISSUE THREAD

**Issue by ODiogoSilva** [kivy/kivy#3928]
I am using the kivy git master branch and Ubuntu 14.04. When I run the sample scrollview widget (kivy/examples/widgets/scrollview.py) and use my laptop's mouse pad double finger scroll, every time I make an horizontal scroll, kivy seems to interpret it as a mouse left click and triggers the `on_touch` event of the buttons. However, this issues does not occur in my other laptop running Arch Linux and the same kivy master branch.

I did some digging in the kivy/uix/scrollview.py file, and found that the `touch` variable is handled differently in each system. In Ubuntu, printing `(touch.profile, touch.button)` at the beginning of `on_scroll_start` while scrolling to the left/right using the mouse pad, yields `(['pos', 'button'], 'left')`, whereas in Arch it does not even call `on_scroll_start`. When I left-click, I also get  `(['pos', 'button'], 'left')` in both systems and, therefore, in Ubuntu I cannot distinguish horizontal scrolling from mouse left clicking.

I don't know how the input events are handled in kivy, but if you could point me to the files, I could try to fix this issue. Could this have to do with the drivers for the mouse pad of each laptop?

**Comment by ODiogoSilva** [comment]
After I bit of digging, I went to kivy/core/window/window_sdl2.py and found that the `action` variable in `_mainloop()` yields `mousebuttondown` and `mousebuttonup` when scrolling horizontally with the mouse pad, instead of `mousewheeldown/up`. It appears that, for some reason, the horizontal scrolling is interpreted as a 6th (left scroll) and 7th (right scroll) mouse buttons, as the third element of the `args` variable suggests.

For the moment, I fixed the problem by modifying the code to accommodate the 6th and 7th buttons:

```
            elif action in ('mousebuttondown', 'mousebuttonup'):
                x, y, button = args
                x, y = self._fix_mouse_pos(x, y)
                btn = 'left'
                if button == 3:
                    btn = 'right'
                elif button == 2:
                    btn = 'middle'
                elif button == 6:
                    btn = 'scrollleft'
                elif button == 7:
                    btn = 'scrollright'
```

but this is a very ugly hack that will likely overwrite functions for mouses that actually have the 6th and 7th buttons.

**Comment by dessant** [comment]
It seems https://github.com/kivy/kivy/issues/3609 was not fixed after all.

**Comment by dessant** [comment]
@ODiogoSilva wait, are you using sdl 2.0.4?

**Comment by ODiogoSilva** [comment]
No, it's sdl 2.0.2 installed using the 14.04 repo's (libsdl2-dev, etc).

**Comment by dessant** [comment]
Compiling and using the latest sdl release (2.0.4) should fix your issue.
You'll have to point KIVY_SDL2_PATH to the custom sdl headers and binaries before compiling kivy, then also add it to PATH, for running kivy apps.
https://kivy.org/docs/guide/environment.html#path-control

**Comment by ODiogoSilva** [comment]
Updating to sdl 2.0.4 seems to have fixed the issue. Many thanks!
