### ISSUE TITLE
The procedure entry point  inflateRest2 could not be located in dyanmic link library

### ISSUE THREAD

**Issue by abhigenie92** [kivy/kivy#4184]
When I run the kivy app on a virtualenv.
For installing kivy on the virtual environment I have followed these instructions https://kivy.org/docs/installation/installation-windows.html#installation.
![lj65rqg](https://cloud.githubusercontent.com/assets/12474640/14589388/87f87dc6-04fe-11e6-8b90-e463967b1076.png)

```

Abhishek@ABHISHEK ~/Dropbox/notepad_app/2_Paint (master)
![lj65rqg](https://cloud.githubusercontent.com/assets/12474640/14589391/96aa7fcc-04fe-11e6-819a-08c39f9fc954.png)

$ pip list
Django (1.9.5)
docutils (0.12)
image (1.5.3)
Kivy (1.9.1)
Kivy-Garden (0.1.4)
kivy.deps.glew (0.1.4)
kivy.deps.gstreamer (0.1.5)
kivy.deps.sdl2 (0.1.12)
Pillow (3.2.0)
pip (8.1.1)
PyAudio (0.2.9)
Pygments (2.1.3)
PyInstaller (3.1.1)
pypiwin32 (219)
requests (2.9.1)
setuptools (20.9.0)
Twisted (16.1.1)
wheel (0.29.0)
zope.interface (4.1.3)
```

I have uninstalled and reinstalled everything still the same error.

**Comment by abhigenie92** [comment]
It seems to work after uninstalling  kivy.deps.gstreamer when in virtualenv. (Suggested by @KeyWeeUsr on kivy irc). 
Unsure why though.
Question:
when pyinstaller packages it, it won't include the gstreamer lib as it not in vitrualenv. Will it cause a problem while running the executable on other machines.

**Comment by rsvargas** [comment]
I'm having the same problem, but installing kivy.deps.gstreamer does not have any effect.

**Comment by dessant** [comment]
@KeyWeeUsr, was this fixed?

**Comment by KeyWeeUsr** [comment]
Dunno. The packaging works correctly, but I ended up with the old playbin issue for GST, although I have the latest pyinstaller (i.e. with @matham's edit), so I wonder what's going on there. Anyway, I think it **_might_** be fixed as it loads correctly both SDL2 and [GST stuff](https://github.com/kivy/kivy/blob/master/kivy/lib/gstplayer/_gstplayer.pyx#L230) until it starts loading the actual file, i.e. it correctly does `_gst_init()` in Cython `__init__`, therefore `libpng...` shouldn't be really an issue e.g. like with SDL2 when the Window can't be initialized when missing a similar DLL.

```
>videoplayer.exe
[INFO   ] [Logger      ] Record log in C:\Users\...\.kivy\logs\kivy_17-03-19_35.txt
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Kivy        ] v1.9.2.dev0, git-3e1ea73, 20170315
[INFO   ] [Python      ] v3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)]
[INFO   ] [VideoGstplayer] Using Gstreamer 1.10.2.0
[INFO   ] [Video       ] Provider: gstplayer
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.2.0 - Build 10.18.10.3316'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 4400'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 2
[INFO   ] [GL          ] Shading version <b'4.20 - Build 10.18.10.3316'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[ERROR  ] [Image       ] Error loading texture cityCC0.mpg
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "videoplayer.py", line 26, in <module>
     VideoPlayerApp().run()
   File "site-packages\kivy\app.py", line 828, in run
   File "site-packages\kivy\base.py", line 504, in runTouchApp
   File "site-packages\kivy\core\window\window_sdl2.py", line 659, in mainloop
   File "site-packages\kivy\core\window\window_sdl2.py", line 405, in _mainloop
   File "site-packages\kivy\base.py", line 348, in idle
   File "site-packages\kivy\clock.py", line 588, in tick_draw
   File "kivy\_clock.pyx", line 405, in kivy._clock.CyClockBase._process_events_before_frame (kivy\_clock.c:8381)
   File "kivy\_clock.pyx", line 445, in kivy._clock.CyClockBase._process_events_before_frame (kivy\_clock.c:8255)
   File "kivy\_clock.pyx", line 443, in kivy._clock.CyClockBase._process_events_before_frame (kivy\_clock.c:8176)
   File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (kivy\_clock.c:3490)
   File "site-packages\kivy\uix\video.py", line 176, in _do_video_load
   File "site-packages\kivy\core\video\video_gstplayer.py", line 56, in __init__
   File "site-packages\kivy\core\video\__init__.py", line 84, in __init__
   File "site-packages\kivy\core\video\__init__.py", line 116, in <lambda>
     '''Handle Kivy modules. It will automatically load and instantiate the
   File "site-packages\kivy\core\video\__init__.py", line 113, in _set_filename
   File "site-packages\kivy\core\video\video_gstplayer.py", line 68, in load
   File "kivy\lib\gstplayer\_gstplayer.pyx", line 233, in kivy.lib.gstplayer._gstplayer.GstPlayer.load (kivy\lib/gstplayer\_gstplayer.c:3151)

 kivy.lib.gstplayer._gstplayer.GstPlayerException: Unable to create a playbin
Failed to execute script videoplayer
```

**Comment by alegonzalezc** [comment]
Hi @KeyWeeUsr, I' am having this same issue. Do you know if someone has solved this problem?

**Comment by matham** [comment]
It should be fixed with latest deps and kivy.

**Comment by alegonzalezc** [comment]
Are you sure @matham ? 
Can you reproduce the video app packaging example on windows? ([https://kivy.org/docs/guide/packaging-windows.html#packaging-a-video-app-with-gstreamer](url)) 

Because I have the latest deps and kivy 1.9.2, and I still getting the same problem.

**Comment by matham** [comment]
I thought it was fixed, at least in a virtual env. Not sure about packaging.

**Comment by alegonzalezc** [comment]
It seems that packaging a kivy app with gstreamer on windows it's not workint at the moment. I have tried a bunch of different kivy installations and a bunch of different deps versions, but always get the same error when a try to execute the .exe ... apparently gstreamer is not correctly packaged.

I opened a new issue for that: 
[https://github.com/kivy/kivy/issues/5099](url)

**Comment by Julian-O** [comment]
No reports for many years. Seem to be working.

Closing as stale, but if you are still having the problem, let us know.
