### ISSUE TITLE
Texture bytes shifted by one byte

### ISSUE THREAD

**Issue by overfl0** [kivy/kivy#4678]
This error does not seem to show up on my physical machines, both linux and windows. The place where it shows up is a virtual machine with a windows 7, that you can download here:
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
I've got the VirtualBox image.

After installing python and kivy, when running `demo\pictures\main.py`, it looks like texture bytes are shifted by one byte resulting in the colors being changed:

![kivy_bug](https://cloud.githubusercontent.com/assets/1450333/19476571/38841d32-953a-11e6-9b01-ead4ec466d75.jpg)

Oddly enough, PNG files seem to be unaffected. Only jpegs.

This is always reproducible on that VM.

**Comment by KeyWeeUsr** [comment]
What about master branch (try wheel)? Does it work with a _normal_ version of Windows as a virtual machine used on the same machine?

**Comment by overfl0** [comment]
On the VM, both kivy from wheels (1.9.1) and a compiled master (without gstreamer) 1.9.2-dev give the same result as above.
On a completely different machine (with linux instead of windows and a completely different hardware) the result is also the same in the VM.

On the physical windows machine I can see the colors just fine (tested with a wheel version - 1.9.1). It's the same machine which runs the VM with the colors messed up.

**Comment by overfl0** [comment]
Freezing the application with pyinstaller does not change anything. The same exe run on the physical machine works fine but has the colors shifted in the VM.

By running the two programs side by side, I also noticed a shift in the texture of a Label(!). See attached image for details. So this is not a jpeg issue but some kind of texture issue. As I said before, if I change the background of the program to display a png image, the colors stay the same (the label, however is still shifted, of course).

![2016-10-27_23h55_12](https://cloud.githubusercontent.com/assets/1450333/19787139/6cd4c438-9ca1-11e6-843a-c132574ab1e7.png)

**Comment by KeyWeeUsr** [comment]
Most likely related to some low-level stuff. Don't want to say something stupid, maybe SDL2 only, or even directly openGL related, but I'm really not sure. What about drivers of GPU? Do they work correctly with other stuff? Try [testing](http://superuser.com/q/397289/571014) it.

Maybe [report](https://github.com/kivy/kivy/blob/master/kivy/tools/report.py) will tell more.

**Comment by overfl0** [comment]
Report: https://gist.github.com/f2da89233a9941544b007f5d20424193

**Comment by KeyWeeUsr** [comment]
Is it Chromebook you run the VM at or how did these values get there?

```
GL Vendor: Humper
GL Renderer: Chromium
GL Version: 2.1 Chromium 1.9
GL Extensions: None
```

**Comment by overfl0** [comment]
No idea how they did get there. It's a regular PC with Windows 7 and a 4 year old Nvidia graphics card.

I'm using a vagrant image from modern.ie to create a VirtualBox windows 7 (the version with IE9 but that doesn't matter) with the vagrant file almost verbatim (no changes relating to graphics).

To recreate the EXACT same VM I have, get this vagrant file: https://github.com/overfl0/Bulletproof-Build-Environment/blob/master/Vagrantfile
comment out the provisionning command at the end.

And then do: (assuming you have virtualbox)
```
vagrant box add Windows7_ie9 http://aka.ms/vagrant-win7-ie9
vagrant up
```

**Comment by tito** [comment]
This is not a shift by one byte, or your texture will goes completly wrong. This is an issue with RGBA/BGRA issue. I got trouble before with VirtualBox as well, and didn't find a way to solve it, as our code seems completly valid and ok.

**Comment by overfl0** [comment]
Hey! Just a heads up: I revisited this issue and it certainly *IS* a shift by one byte and what's interesting is that alpha values seem to be ignored in this shift. I'm not ruling out a VirtualBox driver issue, of course.

Anyway, I managed to "fix" my texture by using the following code:
```python
        arr = array.array('B', texture.pixels[:])

        lastB = arr[-2]  # rg|B|a
        for pos in xrange(len(arr) - 4, -1, -4):  # Iterate backwards, every 4 bytes
            arr[pos + 0], arr[pos + 1], arr[pos + 2] = arr[pos - 2], arr[pos + 0], arr[pos + 1]

        arr[0] = lastB

        image.texture.blit_buffer(arr, colorfmt='rgba', bufferfmt='ubyte')
```
Of course, it's just a POC to verify whether what I was saying was true - not production code.

----------

Also: 
- red.jpg shows as blue
- green.jpg shows as red
- blue.jpg shows as green

So this definitely rules out RGBA/BGRA issues, since we're dealing with GBRA here (if anything).

------

Yet another observation:
If I open `blue.png`, `self.texture.pixels` contains the values: `\x00\x00\xff\xff` (correct).

Then, if I open `blue.jpg` with pillow and then do a img.tobytes(), I get an RGB string that contains the values `\x00\x00\xfe` (correct).
Then, after doing:

```python
self.texture.blit_buffer(img.tobytes(), colorfmt='rgb', bufferfmt='ubyte')
```

`self.texture.pixels` returns `\x00\xfe\x00\xff` values (r**G**b**A**).

So at least the blitting operation is working wrong (for the record: `self.texture.colorfmt` was `rgba` before blitting). I don't know about the others. I also still don't know why png images are loading just fine.

Any ideas?

**Comment by matham** [comment]
[This code](https://github.com/kivy/kivy/blob/master/kivy/graphics/texture.pyx#L920) is called when you blit. That code may call [this function](https://github.com/kivy/kivy/blob/master/kivy/graphics/img_tools.pxi#L10) which does some conversions of the buffer. That conversion may be the cause of the problem. I'd put print statements there to see what is going on there.

**Comment by overfl0** [comment]
Well, this doesn't look good because everything seems to be running fine:
`cdata` [being passed here](https://github.com/kivy/kivy/blob/master/kivy/graphics/texture.pyx#L1008) is `\x00\x00\xfe`

If, just after that call, I do a `print repr(Fbo(size=self.size, texture=self).pixels[:4])`  (I just hope I'm calling the right functions; it's the first time I'm diving this deep into Kivy), I get `\x00\xfe\x00\xff`.

Is there any chance of this **not** being an OpenGL driver issue? :(

**Comment by matham** [comment]
It would kind of seem that way, as `pixels` just returns what [gl returns](https://github.com/kivy/kivy/blob/master/kivy/graphics/fbo.pyx#L439). But I dunno that much about gl so maybe we're handling something incorrectly when passing buffers that are rgb to rgba texture.

**Comment by bionoid** [comment]
Possibly fixed by #5300, please test the PR if possible

**Comment by overfl0** [comment]
Hey @bionoid !
I rebuilt only Kivy (by doing a `pip uninstall` and then `pip install .\kivy`, I haven't touched any kivy.deps.*) and I've seen no changes, unfortunately - the colors are still shifted and the pixels in the Labels are still not right.

**Comment by bionoid** [comment]
Thanks for testing @overfl0, unfortunately I was not able to replicate the problem using the VM (I didn't use vagrant though, and I updated guest additions before testing..). It looks okay for me - https://i.imgur.com/1Srprj5.png

You did manually check out the branch from my kivy fork, right? (the PR is not merged) .. There is also a separate `bgr_pitchalign` branch that was written speculatively, because I came across some code path that would end up there with aligned data. Sadly I forgot all the details about this :) But it would cause shifts, but not as consistent as in your screenshot (should get offset per row)... But just to rule it out, if you are in the mood, please try them together,

* `git clone https://github.com/bionoid/kivy.git`, `cd kivy`
* `git checkout sdl2_image_pixelformat_squashed`
* `git checkout -b test`
* `git merge bgr_pitchalign`
* Then uninstall/install again

**Comment by overfl0** [comment]
Sure, I'll try again, maybe not reusing the old VM, as I did yesterday but by creating everything from scratch - AFAIK the VMs have also been updated in the meantime by Microsoft so maybe they have fixed those issues themselves a few months ago and I just didn't notice. I'll also update VirtualBox and all the drivers inside the guest.

I'm saying that especially because you said you weren't able to replicate the issue even though I did that on several computers with different GFX cards and operating systems back then (Win7+Nvidia, Ubuntu+Intel)

FYI: I did check your branch from your repo for the tests (pixelformat, not pitchalign)

**Comment by Julian-O** [comment]
@overfl0: Did you get to test this again? Is the problem still occurring?
