### ISSUE TITLE
Unable to get a Windows

### ISSUE THREAD

**Issue by fui86** [kivy/kivy#5360]
Hi, i've installed Kivy on the new relase of Jessie (Stretch).
Now, when i lounch videoplayer.py i see this error:

[WARNING] [Config      ] Older configuration version detected (0 instead of 20)
[WARNING] [Config      ] Upgrading configuration in progress.
[INFO   ] [Logger      ] Record log in /root/.kivy/logs/kivy_17-08-31_0.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-500de18, 20170831
[INFO   ] [Python      ] v2.7.13 (default, Jan 19 2017, 14:48:08)
[GCC 6.3.0 20170124]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif                                           (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [VideoGstplayer] Using Gstreamer 1.10.4.0
[INFO   ] [Video       ] Provider: gstplayer
[INFO   ] [Window      ] Provider: egl_rpi
libEGL warning: DRI3: xcb_connect failed
libEGL warning: DRI2: xcb_connect failed
libEGL warning: DRI2: xcb_connect failed
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
error: XDG_RUNTIME_DIR not set in the environment.
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
egl_rpi - EGLError: EGL_NOT_INITIALIZED (code x3001)
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/__init__.py", line 67,                                           in core_select_lib
    cls = cls()
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/__init__.py", li                                          ne 949, in __init__
    self.create_window()
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_egl_rpi.p                                          y", line 38, in create_window
    self._create_egl_context(self.win, 0)
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_egl_rpi.p                                          y", line 68, in _create_egl_context
    egl.Initialise(display)
  File "kivy/lib/vidcore_lite/egl.pyx", line 352, in kivy.lib.vidcore_lite.egl.I                                          nitialise (/tmp/pip-6kvoQv-build/kivy/lib/vidcore_lite/egl.c:2591)
  File "kivy/lib/vidcore_lite/egl.pyx", line 322, in kivy.lib.vidcore_lite.egl.r                                          aise_egl_error (/tmp/pip-6kvoQv-build/kivy/lib/vidcore_lite/egl.c:2168)

sdl2 - RuntimeError: No available video device
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/__init__.py", line 67,                                           in core_select_lib
    cls = cls()
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py",                                           line 140, in __init__
    super(WindowSDL, self).__init__()
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/__init__.py", li                                          ne 949, in __init__
    self.create_window()
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py",                                           line 269, in create_window
    self.fullscreen, resizable, state)
  File "kivy/core/window/_window_sdl2.pyx", line 84, in kivy.core.window._window                                          _sdl2._WindowSDL2Storage.setup_window (/tmp/pip-6kvoQv-build/kivy/core/window/_w                                          indow_sdl2.c:2390)
  File "kivy/core/window/_window_sdl2.pyx", line 57, in kivy.core.window._window                                          _sdl2._WindowSDL2Storage.die (/tmp/pip-6kvoQv-build/kivy/core/window/_window_sdl                                          2.c:1967)

x11 - ImportError: No module named window_x11
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/__init__.py", line 59,                                           in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL] [App         ] Unable to get a Window, abort.

Can you help me?

**Comment by Shepsi** [comment]
Sorry, not really a help but I wanted to add that I also have major problems getting kivy running on jessie (stretch). I was already afraid when I saw that there was a new raspbian version (which, in the past was bad for installing kivy). Now even kivy has a new version...

The problem above accured and was fixed by switching from ssh to the real pi and attaching a monitor/mouse etc to it. But then only other errors relating pygames and so on occured.

@Developers
Please update your raspbian installation tutorial if possible... It was already out of date and didn't worked before version 1.10. (You have to downgrade to Cython 0.20 instead of installing the newst version) Now I can't even install it anymore because there are no insights about the new version...

**Comment by KeyWeeUsr** [comment]
error: XDG_RUNTIME_DIR not set in the environment.
    sdl2 - RuntimeError: No available video device

I'm not sure, but it seems to me like you're running just the console and not the window manager. I got a similar error long ago in Travis when I didn't run the window manager / display.

**Comment by submax82** [comment]
I have the same problem on raspbian Stretch lite version (without GUI).
I want run kivy without Xorg... is possible? what is missing for work?

**Comment by submax82** [comment]
#5362

The foundation renamed some libraries in **August 2017** to clear up some confusion.

**libGLESv2.so became libbrcmGLESv2.so
libEGL.so became libbrcmEGL.so**

and so on. Why ? It turns out Mesa ships libraries with exactly the same name and people were gettting confused which libraries were from Mesa and which from Broadcom. This is especially fatal since the libraries Mesa provides are better integrated with X , but less stable and a bit slower (speed has increased dramatically since hardware rendering was added).

reference: https://jp.raspberrypi.org/forums/viewtopic.php?f=68&t=192869

On **kivy >= 1.10.1 is already fixed**, therefore on raspbian Stretch must be used:
`pip install --upgrade --force-reinstall git+https://github.com/kivy/kivy.git@master`

**Comment by KeyWeeUsr** [comment]
Nice findings, especially the date. Perhaps you could include it to the RPi [installation docs](https://kivy.org/docs/installation/installation-rpi.html) as a `.. note::`? I bet it will help someone using stable versions instead of digging through the github issues.

**Comment by submax82** [comment]
if you want i can, but how?

**Comment by KeyWeeUsr** [comment]
@submax82 you can edit [this file](https://github.com/kivy/kivy/blob/master/doc/sources/installation/installation-rpi.rst), check the RST syntax on [this page](http://rst.ninjs.org/) and submit a pull request :)

**Comment by ivopashov** [comment]
I see this is closed but still experience the error.
I am running:
```
sysop@pipaos:~$ cat /etc/*-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
```
also have the latest kivy installed (pip installed from master)
```
sysop@pipaos:~$ cat /usr/local/lib/python2.7/dist-packages/kivy/version.py
# THIS FILE IS GENERATED FROM KIVY SETUP.PY
__version__ = '1.10.1.dev0'
__hash__ = 'ae3665c32e1fdb9b7564aa6bbceeb58b5cd09ec5'
__date__ = '20180423'
```
and when i run a basic examples as `python /usr/local/share/kivy-examples/demo/camera/main.py` i get
```
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
egl_rpi - ImportError: cannot import name bcm
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

sdl2 - RuntimeError: No available video device
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/__init__.py", line 67, in core_select_lib
    cls = cls()
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 140, in __init__
    super(WindowSDL, self).__init__()
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/__init__.py", line 960, in __init__
    self.create_window()
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 272, in create_window
    self.fullscreen, resizable, state)
  File "kivy/core/window/_window_sdl2.pyx", line 93, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window
  File "kivy/core/window/_window_sdl2.pyx", line 66, in kivy.core.window._window_sdl2._WindowSDL2Storage.die

x11 - ImportError: No module named window_x11
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL] [App         ] Unable to get a Window, abort.
```

**Comment by joeseegmiller** [comment]
I am seeing the exact same error as @ivopashov on kivy 1.10.1.dev0 using a Raspberry Pi 3B+ and Raspbian Stretch

The fix presented above does not fix it.

**Comment by kuzeyron** [comment]
Hello! As a start. I have never got the Kivy Camera to run on my Desktop PC.
So you would probably need to check the source code for it.
Using PiCamera python-bindings you might find more success with.

If you set the OpenGL driver to Full KMS. You do that by running `sudo raspi-config`.
And add this to `/home/pi/.bashrc`: `export DISPLAY=:0.0`
`sudo reboot` or just run in Terminal: `source ~/.bashrc`
It should do the trick and even hide FBO errors.
I'm doing research regarding these issues. Hopefully tomorrow is the day for me to know the real answer for everything!

**Comment by Graveen** [comment]
Hi, i'm more or less in this case, except i'd like to downgrade from 1.11dev0.
I'm assuming to run with python3 i must use pip3 instead of pip
>> am i right ?
and for downgrading a kivy installed i should use 
>> pip install --upgrade --force-reinstall git+https://github.com/kivy/kivy.git@stable-1.10

**Comment by Neex101** [comment]
I am seeing the exact same error as @ivopashov on kivy 1.10.1 using a Raspberry Pi 3B+ and Raspbian Stretch. 

I am using the official RasPi 7" touchscreen, and python2. Is there any testing I can do to help? Thnx

**Comment by kuzeyron** [comment]
I hope you guys have tried this [Guide](https://kivy.org/doc/stable/installation/installation-rpi.html).
Otherwise Ubuntu Mate is using different drivers for the Graphics. So If Raspbian fails on you that much that you get FBO errors and such. Then I advice you to try out Ubuntu Mate.

**Comment by Neex101** [comment]
@kuzeyron thanks, yes was building from the Kivy.org guide. Can't use Ubuntu Mate, want to use PipaOS for lightweight boot.

**Comment by Neex101** [comment]
OK, it's working for me today:

Hardware: Raspberry Pi 3B+, official 7" touchscreen
OS: Rasbian Stretch Lite, latest release (June 2018) from [here](https://www.raspberrypi.org/downloads/raspbian/)
Following build steps from Kivy.org [here](https://kivy.org/doc/stable/installation/installation-rpi.html) to install latest Kivy globally.
Kivy: 1.11.0.dev0 (@master) git-ce8017c, 20180918
Python: 2.7.13

python /usr/local/share//kivy-examples/demo/showcase/main.py

... runs fine

**Comment by kuzeyron** [comment]
@Neex101 It will work unless you try running ScreenManager. I hit easily the memory leak.
But on the other hand, Kivy runs smoothly for me as well on ArchLinux which is on my Pi3B+.
But I'm only using Carousel so that's fine.

**Comment by Neex101** [comment]
@kuzeyron  hi! So Kivy won't work on 3B+ with ScreenManager?? Is it a memory **leak** or just not enough memory? (maybe I can adjust the memory allocated to the GPU?). Is ArchLinux better than Rasbian Stretch Lite for this application, if so why? Many thanks,

**Comment by kuzeyron** [comment]
@Neex101 Ubuntu Mate is known to have working drivers. Raspbian and Arch is using the same drivers.
I haven't looked on Ubuntu Mates drivers on how they compiled it and which syntaxes.
If I or someone else would manage to get the same drivers. Then the drivers could be placed on its own place and Kivy would simply just link it so other users know where to grab it from.

Yes, it's a memory leak. Not sure of the cause. But the Raspberry Pi foundation should be looking at the issue AFAIK. This is what I know: [raspberrypi.org/forums](https://lb.raspberrypi.org/forums/viewtopic.php?t=216804)

**Comment by Neex101** [comment]
Wow. I'm shocked... thank you for your very helpful direction. I will try Mate immediately.

**Comment by kuzeyron** [comment]
No I don't have any particular version. But as long as the drivers are using "llvmpipe" it should be good to go.

**Comment by HarijotSidhu** [comment]
I had the same issue solved it by changing "multisamples=2" to "multisamples=0" in config.ini present in directory C:\<username>\.kivy\ if multisamples is beforehand equal to 0 change it to 2

**Comment by Graveen** [comment]
Thank you. On my side it was an issue with full screen initialisation that was working on Windows but not on RPi. I'll try the multisamples option, too.

**Comment by jasonakon** [comment]
My issue is solved by changing the screen resolution of your raspberry-pi become smaller.

**Comment by Adem-hub** [comment]
U are all des piiiites
