### ISSUE TITLE
fail install on mac os 10.13.3 (command 'clang' failed with exit status 1)

### ISSUE THREAD

**Issue by foozzi** [kivy/kivy#5653]
### Versions

* Python: 3.6
* OS: macos 10.13.3
* Kivy: latest stable
* Kivy installation method: homebrew with pip

### Description
problem like this https://github.com/kivy/kivy/issues/5400

i'm try install from this guide https://kivy.org/docs/installation/installation-osx.html#using-homebrew-with-pip but have error 

### Code and Logs

```python
                                                                                      ^
    /private/var/folders/s9/__8s8mp51rx47r5m1jv5tlc80000gn/T/pip-build-avx_09_r/kivy/kivy/core/audio/audio_sdl2.c:5262:69: error: use of undeclared identifier 'MIX_INIT_MODPLUG'; did you mean 'MIX_INIT_MOD'?
      __pyx_t_2 = ((__pyx_v_4kivy_4core_5audio_10audio_sdl2_mix_flags & MIX_INIT_MODPLUG) != 0);
                                                                        ^~~~~~~~~~~~~~~~
                                                                        MIX_INIT_MOD
    /usr/local/include/SDL2/SDL_mixer.h:80:5: note: 'MIX_INIT_MOD' declared here
        MIX_INIT_MOD    = 0x00000002,
        ^
    3 errors generated.
     error: command 'clang' failed with exit status 1

    ----------------------------------------
Command "/Users/igortkachenko/Tools/kivy-designer/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/s9/__8s8mp51rx47r5m1jv5tlc80000gn/T/pip-build-avx_09_r/kivy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/s9/__8s8mp51rx47r5m1jv5tlc80000gn/T/pip-as0ay57g-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/igortkachenko/Tools/kivy-designer/venv/bin/../include/site/python3.6/kivy" failed with error code 1 in /private/var/folders/s9/__8s8mp51rx47r5m1jv5tlc80000gn/T/pip-build-avx_09_r/kivy/
```

**Comment by Mileem** [comment]
Hello !

You must have homebrew and Python 3.6 (with pip) already installed

## Install Kivy 🦖

You need to install all the requirements for Kivy (Gstreamer, SDL2, etc.)
Don't forget to add the gst-plugins with libvorbis for play .mp3 and .ogg files !

```
brew install pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer gstreamer

brew install --with-libvorbis gst-plugins-{base,good,bad,ugly}
```

Now install Kivy, I don't know why but only the dev version is ok 🙈
```
sudo pip install Cython==0.26.1

sudo pip install --user --verbose https://github.com/kivy/kivy/archive/master.zip
```

🎉 Successfully installed Kivy-1.10.1.dev0 🎉

Tell me if you have other problems.

Bye.

**Comment by bionoid** [comment]
The error you report is due to a breaking change in sdl2-mixer v2.0.2. A fix has been merged to master branch, but not made it to stable release yet. You also cannot build Kivy stable with Cython version 0.26 (I think it needs 0.25). The simplest fix for both issues is:

    pip install kivy==master

**Comment by dolang** [comment]
@npryce I'm not sure it's possible to do it like that.  If you specify `<package>==<version>`  doesn't pip just look for a package on PyPI? I don't think it knows about GitHub (or any other repository).  If you want to point pip to the master branch here, you need to do something like:
```
pip install git+https://github.com/kivy/kivy@master#egg=Kivy
```
or what I myself prefer:
```
git clone https://github.com/kivy/kivy
cd kivy
pip install .
```
also, if you install the latter with ` pip -e` then the repository will be installed in "developer" or "editable" mode, and you can fetch new revisions without reinstalling (you'd still have to rebuild if there are changes to Cython files in a revision).

**Note:** in any case you need a suitable version of **Cython** before they can be installed like this.

**Comment by npryce** [comment]
Thanks for your response. That was very helpful and I have Kivy installed now.

**Comment by jabdoa2** [comment]
A simpler way would be: pip install git+https://github.com/kivy/kivy.git@master

**Comment by Zujiry** [comment]
Even though I tried all the steps above I have the same problem still.

Python: 3.6.5
OS: macOS Sierra 10.12.6
Kivy: latest stable
Kivy installation method: homebrew with pip

I can not install kivy


The error (-end, as there are many)

`In file included from /private/var/folders/85/ndbqsh5n5s79pz0564vvbvcr0000gn/T/pip-D5TGyb-build/kivy/core/text/_text_sdl2.c:485:
    In file included from /Library/Frameworks/SDL2_image.framework/Headers/SDL_image.h:27:
    In file included from /usr/local/include/SDL2/SDL.h:36:
    In file included from /usr/local/include/SDL2/SDL_audio.h:32:
    /usr/local/include/SDL2/SDL_error.h:59:5: error: redefinition of enumerator 'SDL_EFWRITE'
        SDL_EFWRITE,
        ^
    /Library/Frameworks/SDL2.framework/Headers/SDL_error.h:59:5: note: previous definition is here
        SDL_EFWRITE,
        ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
     error: command 'clang' failed with exit status 1`

**Comment by mathmost** [comment]
ERROR: Command errored out with exit status 1: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 /Users/mac/Library/Python/3.8/lib/python/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/50/q_zy_g3j6mbb44jg1bn64r_h0000gn/T/pip-build-env-crc6v4hy/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i http://pypi.douban.com/simple/ --trusted-host pypi.tuna.tsinghua.edu.cn -- setuptools wheel 'cython>=0.24,<=0.29.21,!=0.27,!=0.27.2' 'kivy_deps.gstreamer_dev~=0.3.1; sys_platform == "win32"' 'kivy_deps.sdl2_dev~=0.3.1; sys_platform == "win32"' 'kivy_deps.glew_dev~=0.3.0; sys_platform == "win32"' 'kivy_deps.gstreamer~=0.3.1; sys_platform == "win32"' 'kivy_deps.sdl2~=0.3.1; sys_platform == "win32"' 'kivy_deps.glew~=0.3.0; sys_platform == "win32"' Check the logs for full command output.
