### ISSUE TITLE
App screen is blank before resize running `python main.py` on Mac Mojave

### ISSUE THREAD

**Issue by s1113950** [kivy/kivy#6203]
### Versions

* Python: 3.7.2
* OS: Mac
* Kivy: 1.10.1
* Kivy installation method: pip install

### Description

My app used to start up as normal, but now I have to resize the window in order to see things displayed. I'm not sure what changed 😞 . I'm running it with `python main.py` to do some debugging on the Mac (it works fine on startup on my Android phone, and in the iOS simulator).

### Code and Logs

```python
class PilesManager(ScreenManager):
    pass


class PilesApp(App):
    def __init__(self, *args, **kwargs):
        self.args = kwargs.pop('args')
        super().__init__(*args, **kwargs)

    def build(self):
        self.p = PilesManager(transition=FallOutTransition())
        self.root = RootWidget(manager=self.p)
        self.root.add_widget(self.p)

        login_screen = LoginScreen(root=self.root)
        player_screen = PlayerScreen(root=self.root)
        game_screen = GameScreen(flags=self.args, root=self.root)

        # reference gamepage for later
        self.root.game_screen = game_screen
        self.root.player_screen = player_screen

        self.p.add_widget(login_screen)
        self.p.add_widget(player_screen)
        self.p.current = "login"
        # self.p.switch_to(login_screen)
        # self.p.add_widget(game_screen)

        # self.p.switch_to(login_screen)

        return self.root


class CustomExceptionHandler(ExceptionHandler):
    def handle_exception(self, inst):
        # on computer and typing ctrl-c to kill program
        if isinstance(inst, KeyboardInterrupt):
            return ExceptionManager.RAISE

        traceback.print_exc()
        # make inst easier to read on phone
        err = ""
        for idx, char in enumerate(str(inst)):
            err += char
            if idx % 30 == 0 and idx != 0:
                err += '\n'
        make_generic_popup("ERROR: {}".format(err))
        return ExceptionManager.PASS


if __name__ == '__main__':
    ExceptionManager.add_handler(CustomExceptionHandler())

    PilesApp(args={}).run()

```

```
(app-venv) robertso@robertso-mac02:~/piles/app-piles$ python main.py
Purge log fired. Analysing...
Purge 2 log files
Purge finished!
[INFO   ] [Logger      ] Record log in /Users/robertso/.kivy/logs/kivy_19-03-14_7.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.2 (default, Feb  4 2019, 20:01:21)
[Clang 10.0.0 (clang-1000.11.45.5)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'2.1 ATI-2.0.36'>
[INFO   ] [GL          ] OpenGL vendor <b'ATI Technologies Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'AMD Radeon Pro 560 OpenGL Engine'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
```

When I resize the window no logs show but my login page gets rendered.

EDIT: I removed some `args` things from my code because I was doing it the wrong way; it didn't affect the outcome

**Comment by s1113950** [comment]
Just tried to add a `sleep(2)` before the `return self.root` call, and it went to a white screen, then flashed my login page for a split second before going black!

**Comment by s1113950** [comment]
Another thing I tried: rather than doing `self.p.current = login_screen` I tried doing `self.p.switch_to(login_screen)` but then it called the `on_pre_enter` function of `player_screen` because that was the first widget added

**Comment by tito** [comment]
Can you tell us which OSX are you using, SDL2 version, and Kivy (last stable or somewhere in master?)
If possible, try master?

**Comment by akshayaurora** [comment]
I had a similar issue some time ago, was fixed when either when I updated the os again or by moving to master kivy. Can't reproduce anymore so don't know what fixed it.

as @tito stated, could you try with kivy master ?

**Comment by s1113950** [comment]
OSX `10.14`
Kivy `v1.10.1`
sdl2 `stable 2.0.9 (bottled), HEAD`

I recently upgraded my OS to Mojave (from Sierra); maybe that's why it worked before?
Just tried with `v1.11.0.dev0, git-Unknown, 20190315` of Kivy and still no luck

**Comment by IsaacMe** [comment]
I've had exactly the same problem on macOS `10.14`. But I just updated to `10.14.4` and it now works like a charm on Kivy `v1.10.1`

**Comment by s1113950** [comment]
Mac upgrade fixed this for me as well!
